export enum ActionType {
  SET_CURRENT_USER = "SET_CURRENT_USER",
  GET_PROFILE = "GET_PROFILE",
  PROFILE_LOADING = "PROFILE_LOADING",
  GET_ERRORS = "GET_ERRORS",
  CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE",
  GET_PROFILES = "GET_PROFILES",
  POST_LOADING = "POST_LOADING",
  GET_POSTS = "GET_POSTS",
  GET_POST = "GET_POsT",
  ADD_POST = "ADD_POST",
  DELETE_POST = "DELETE_POST",
}
